image: tdeknecht/aws:latest
before_script:
  - aws --version
  - terraform --version
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set region us-east-1

stages:
 - plan
 - apply
 - build

plan:
  tags:
    - base
  stage: plan
  script:
    - cd src/terraform/ && terraform init && terraform plan

apply:
  tags:
    - base
  stage: apply
  script:
    - cd src/terraform/ && terraform init && terraform apply -auto-approve
  dependencies:
    - plan
  only:
    refs:
      - master
  when: manual

build:
  tags:
    - base
  stage: build
  script:
    - cd src/www/ && aws s3 sync . s3://citl.club --delete
    - sleep 5
    - aws cloudfront create-invalidation --distribution-id E16OFBJW5KU8T7 --paths "/scorecards.html" "/index.html" "/downloads.html"
  dependencies:
    - apply
  only:
    refs:
      - master
  when: manual
  